import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CommonLayOut from "@/components/commonLayOut";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
          {/* <head>
  <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
       </head> */}
       
        <CommonLayOut>
        {children}
        </CommonLayOut>
        
       
      </body>
    </html>
  );
}
